import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {AppProvider} from "@/AppContext";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Price Broker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-slate-700 h-14 flex justify-center items-center">
            <span className="text-xl font-bold text-amber-400">
              Price Broker
            </span>
        </nav>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  )
}
